name: jcore_fluttify
description: A `JCore` Component, Powered By `Fluttify` Engine.
version: 0.1.0
author: yohom <yohombao@qq.com>
homepage: https://github.com/fluttify-project/jcore_fluttify

environment:
  sdk: ">=2.6.0 <3.0.0"
  flutter: ">=1.12.13 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  foundation_fluttify: ^0.8.11-dev.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: me.yohom.jcore_fluttify
        pluginClass: JcoreFluttifyPlugin
      ios:
        pluginClass: JcoreFluttifyPlugin