//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

#import "JcoreFluttifyPlugin.h"

NS_ASSUME_NONNULL_BEGIN

@interface JcoreFluttifyPlugin (SubHandlerCustom)
- (NSDictionary<NSString*, Handler>*) getSubHandlerCustom;
@end

NS_ASSUME_NONNULL_END
