// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import, unused_local_variable, dead_code, unnecessary_cast
//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

import 'dart:io';

import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';
import 'package:jcore_fluttify/src/android/android.export.g.dart';

import 'package:foundation_fluttify/foundation_fluttify.dart';

// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import
extension TypeOpJcoreFluttifyAndroid on Object {
  // type check
  Future<bool> is__<T>() async {
    final typeName = T.toString();
    if (RegExp('(List<)?(String|int|double)(>)?|(Map<String,(String|int|double)>)').hasMatch(typeName)) {
      return this is T;
    }
    else if (T == cn_jiguang_net_DefaultHostVerifier) {
      final result = await MethodChannel('me.yohom/jcore_fluttify').invokeMethod('RefClass::isKindOfcn_jiguang_net_DefaultHostVerifier', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == cn_jiguang_net_SSLTrustManager) {
      final result = await MethodChannel('me.yohom/jcore_fluttify').invokeMethod('RefClass::isKindOfcn_jiguang_net_SSLTrustManager', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == cn_jiguang_net_HttpRequest) {
      final result = await MethodChannel('me.yohom/jcore_fluttify').invokeMethod('RefClass::isKindOfcn_jiguang_net_HttpRequest', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == cn_jiguang_net_HttpUtils) {
      final result = await MethodChannel('me.yohom/jcore_fluttify').invokeMethod('RefClass::isKindOfcn_jiguang_net_HttpUtils', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == cn_jiguang_net_HttpResponse) {
      final result = await MethodChannel('me.yohom/jcore_fluttify').invokeMethod('RefClass::isKindOfcn_jiguang_net_HttpResponse', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == cn_jiguang_internal_JConstants) {
      final result = await MethodChannel('me.yohom/jcore_fluttify').invokeMethod('RefClass::isKindOfcn_jiguang_internal_JConstants', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == cn_jiguang_internal_JCoreHelperAction) {
      final result = await MethodChannel('me.yohom/jcore_fluttify').invokeMethod('RefClass::isKindOfcn_jiguang_internal_JCoreHelperAction', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == cn_jiguang_internal_JCoreInternalHelper) {
      final result = await MethodChannel('me.yohom/jcore_fluttify').invokeMethod('RefClass::isKindOfcn_jiguang_internal_JCoreInternalHelper', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == cn_jiguang_internal_ActionManager) {
      final result = await MethodChannel('me.yohom/jcore_fluttify').invokeMethod('RefClass::isKindOfcn_jiguang_internal_ActionManager', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == cn_jiguang_android_IDataShare) {
      final result = await MethodChannel('me.yohom/jcore_fluttify').invokeMethod('RefClass::isKindOfcn_jiguang_android_IDataShare', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == cn_jiguang_android_IDataShare_Stub) {
      final result = await MethodChannel('me.yohom/jcore_fluttify').invokeMethod('RefClass::isKindOfcn_jiguang_android_IDataShare_Stub', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == cn_jiguang_android_BuildConfig) {
      final result = await MethodChannel('me.yohom/jcore_fluttify').invokeMethod('RefClass::isKindOfcn_jiguang_android_BuildConfig', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == cn_jiguang_dy_Protocol) {
      final result = await MethodChannel('me.yohom/jcore_fluttify').invokeMethod('RefClass::isKindOfcn_jiguang_dy_Protocol', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == cn_jiguang_api_JDispatchAction) {
      final result = await MethodChannel('me.yohom/jcore_fluttify').invokeMethod('RefClass::isKindOfcn_jiguang_api_JDispatchAction', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == cn_jiguang_api_JActionExtra) {
      final result = await MethodChannel('me.yohom/jcore_fluttify').invokeMethod('RefClass::isKindOfcn_jiguang_api_JActionExtra', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == cn_jiguang_api_utils_ByteBufferUtils) {
      final result = await MethodChannel('me.yohom/jcore_fluttify').invokeMethod('RefClass::isKindOfcn_jiguang_api_utils_ByteBufferUtils', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == cn_jiguang_api_utils_OutputDataUtil) {
      final result = await MethodChannel('me.yohom/jcore_fluttify').invokeMethod('RefClass::isKindOfcn_jiguang_api_utils_OutputDataUtil', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == cn_jiguang_api_utils_ProtocolUtil) {
      final result = await MethodChannel('me.yohom/jcore_fluttify').invokeMethod('RefClass::isKindOfcn_jiguang_api_utils_ProtocolUtil', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == cn_jiguang_api_JRequest) {
      final result = await MethodChannel('me.yohom/jcore_fluttify').invokeMethod('RefClass::isKindOfcn_jiguang_api_JRequest', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == cn_jiguang_api_JResponse) {
      final result = await MethodChannel('me.yohom/jcore_fluttify').invokeMethod('RefClass::isKindOfcn_jiguang_api_JResponse', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == cn_jiguang_api_JCoreInterface) {
      final result = await MethodChannel('me.yohom/jcore_fluttify').invokeMethod('RefClass::isKindOfcn_jiguang_api_JCoreInterface', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == cn_jiguang_api_JCoreManager) {
      final result = await MethodChannel('me.yohom/jcore_fluttify').invokeMethod('RefClass::isKindOfcn_jiguang_api_JCoreManager', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == cn_jiguang_api_BaseLogger) {
      final result = await MethodChannel('me.yohom/jcore_fluttify').invokeMethod('RefClass::isKindOfcn_jiguang_api_BaseLogger', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == cn_jiguang_api_JProtocol) {
      final result = await MethodChannel('me.yohom/jcore_fluttify').invokeMethod('RefClass::isKindOfcn_jiguang_api_JProtocol', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == cn_jiguang_api_MultiSpHelper) {
      final result = await MethodChannel('me.yohom/jcore_fluttify').invokeMethod('RefClass::isKindOfcn_jiguang_api_MultiSpHelper', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == cn_jiguang_analytics_page_ActivityLifecycle) {
      final result = await MethodChannel('me.yohom/jcore_fluttify').invokeMethod('RefClass::isKindOfcn_jiguang_analytics_page_ActivityLifecycle', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == cn_jiguang_analytics_page_PushSA) {
      final result = await MethodChannel('me.yohom/jcore_fluttify').invokeMethod('RefClass::isKindOfcn_jiguang_analytics_page_PushSA', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == cn_jcore_client_android_BuildConfig) {
      final result = await MethodChannel('me.yohom/jcore_fluttify').invokeMethod('RefClass::isKindOfcn_jcore_client_android_BuildConfig', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == cn_jpush_android_service_PushService) {
      final result = await MethodChannel('me.yohom/jcore_fluttify').invokeMethod('RefClass::isKindOfcn_jpush_android_service_PushService', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == cn_jpush_android_service_DActivity) {
      final result = await MethodChannel('me.yohom/jcore_fluttify').invokeMethod('RefClass::isKindOfcn_jpush_android_service_DActivity', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == cn_jpush_android_service_JCommonService) {
      final result = await MethodChannel('me.yohom/jcore_fluttify').invokeMethod('RefClass::isKindOfcn_jpush_android_service_JCommonService', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == cn_jpush_android_service_DataProvider) {
      final result = await MethodChannel('me.yohom/jcore_fluttify').invokeMethod('RefClass::isKindOfcn_jpush_android_service_DataProvider', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == cn_jpush_android_service_AlarmReceiver) {
      final result = await MethodChannel('me.yohom/jcore_fluttify').invokeMethod('RefClass::isKindOfcn_jpush_android_service_AlarmReceiver', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == cn_jpush_android_service_PushReceiver) {
      final result = await MethodChannel('me.yohom/jcore_fluttify').invokeMethod('RefClass::isKindOfcn_jpush_android_service_PushReceiver', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == cn_jpush_android_service_WakedResultReceiver) {
      final result = await MethodChannel('me.yohom/jcore_fluttify').invokeMethod('RefClass::isKindOfcn_jpush_android_service_WakedResultReceiver', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == cn_jpush_android_service_DownloadActivity) {
      final result = await MethodChannel('me.yohom/jcore_fluttify').invokeMethod('RefClass::isKindOfcn_jpush_android_service_DownloadActivity', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == cn_jpush_android_service_DaemonService) {
      final result = await MethodChannel('me.yohom/jcore_fluttify').invokeMethod('RefClass::isKindOfcn_jpush_android_service_DaemonService', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == cn_jpush_android_service_DaemonService_MyBinder) {
      final result = await MethodChannel('me.yohom/jcore_fluttify').invokeMethod('RefClass::isKindOfcn_jpush_android_service_DaemonService_MyBinder', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == cn_jpush_android_service_DataShare) {
      final result = await MethodChannel('me.yohom/jcore_fluttify').invokeMethod('RefClass::isKindOfcn_jpush_android_service_DataShare', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == cn_jpush_android_service_DownloadProvider) {
      final result = await MethodChannel('me.yohom/jcore_fluttify').invokeMethod('RefClass::isKindOfcn_jpush_android_service_DownloadProvider', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == android_content_Context) {
      final result = await MethodChannel('me.yohom/jcore_fluttify').invokeMethod('RefClass::isKindOfandroid_content_Context', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == android_content_Intent) {
      final result = await MethodChannel('me.yohom/jcore_fluttify').invokeMethod('RefClass::isKindOfandroid_content_Intent', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == android_content_ContentProvider) {
      final result = await MethodChannel('me.yohom/jcore_fluttify').invokeMethod('RefClass::isKindOfandroid_content_ContentProvider', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == android_app_Application) {
      final result = await MethodChannel('me.yohom/jcore_fluttify').invokeMethod('RefClass::isKindOfandroid_app_Application', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == android_app_Notification) {
      final result = await MethodChannel('me.yohom/jcore_fluttify').invokeMethod('RefClass::isKindOfandroid_app_Notification', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == android_app_Activity) {
      final result = await MethodChannel('me.yohom/jcore_fluttify').invokeMethod('RefClass::isKindOfandroid_app_Activity', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == android_app_PendingIntent) {
      final result = await MethodChannel('me.yohom/jcore_fluttify').invokeMethod('RefClass::isKindOfandroid_app_PendingIntent', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == android_os_Bundle) {
      final result = await MethodChannel('me.yohom/jcore_fluttify').invokeMethod('RefClass::isKindOfandroid_os_Bundle', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == android_os_Binder) {
      final result = await MethodChannel('me.yohom/jcore_fluttify').invokeMethod('RefClass::isKindOfandroid_os_Binder', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == android_view_View) {
      final result = await MethodChannel('me.yohom/jcore_fluttify').invokeMethod('RefClass::isKindOfandroid_view_View', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == android_view_SurfaceView) {
      final result = await MethodChannel('me.yohom/jcore_fluttify').invokeMethod('RefClass::isKindOfandroid_view_SurfaceView', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == android_view_ViewGroup) {
      final result = await MethodChannel('me.yohom/jcore_fluttify').invokeMethod('RefClass::isKindOfandroid_view_ViewGroup', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == android_graphics_Point) {
      final result = await MethodChannel('me.yohom/jcore_fluttify').invokeMethod('RefClass::isKindOfandroid_graphics_Point', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == android_graphics_PointF) {
      final result = await MethodChannel('me.yohom/jcore_fluttify').invokeMethod('RefClass::isKindOfandroid_graphics_PointF', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == android_graphics_Bitmap) {
      final result = await MethodChannel('me.yohom/jcore_fluttify').invokeMethod('RefClass::isKindOfandroid_graphics_Bitmap', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == android_widget_ImageView) {
      final result = await MethodChannel('me.yohom/jcore_fluttify').invokeMethod('RefClass::isKindOfandroid_widget_ImageView', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == java_io_File) {
      final result = await MethodChannel('me.yohom/jcore_fluttify').invokeMethod('RefClass::isKindOfjava_io_File', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == android_location_Location) {
      final result = await MethodChannel('me.yohom/jcore_fluttify').invokeMethod('RefClass::isKindOfandroid_location_Location', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == android_view_MotionEvent) {
      final result = await MethodChannel('me.yohom/jcore_fluttify').invokeMethod('RefClass::isKindOfandroid_view_MotionEvent', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == android_graphics_drawable_Drawable) {
      final result = await MethodChannel('me.yohom/jcore_fluttify').invokeMethod('RefClass::isKindOfandroid_graphics_drawable_Drawable', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == android_widget_FrameLayout) {
      final result = await MethodChannel('me.yohom/jcore_fluttify').invokeMethod('RefClass::isKindOfandroid_widget_FrameLayout', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == android_widget_TextView) {
      final result = await MethodChannel('me.yohom/jcore_fluttify').invokeMethod('RefClass::isKindOfandroid_widget_TextView', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == android_widget_LinearLayout) {
      final result = await MethodChannel('me.yohom/jcore_fluttify').invokeMethod('RefClass::isKindOfandroid_widget_LinearLayout', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == android_widget_RelativeLayout) {
      final result = await MethodChannel('me.yohom/jcore_fluttify').invokeMethod('RefClass::isKindOfandroid_widget_RelativeLayout', {'refId': (this as Ref).refId});
      return result;
    }
    else if (T == android_util_Pair) {
      final result = await MethodChannel('me.yohom/jcore_fluttify').invokeMethod('RefClass::isKindOfandroid_util_Pair', {'refId': (this as Ref).refId});
      return result;
    }
  }

  // type cast
  T as__<T>() {
    final typeName = T.toString();
    // jsonable 直接造型 返回
    if (RegExp('(List<)?(String|int|double)(>)?|(Map<String,(String|int|double)>)').hasMatch(typeName)) {
      return this as T;
    }
    // 如果是Ref类的cast, 那么取其refId, 如果本身是refId, 那么直接使用(int)
    else if (T == cn_jiguang_net_DefaultHostVerifier) {
      return (cn_jiguang_net_DefaultHostVerifier()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'jcore_fluttify') as T;
    }
    else if (T == cn_jiguang_net_SSLTrustManager) {
      return (cn_jiguang_net_SSLTrustManager()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'jcore_fluttify') as T;
    }
    else if (T == cn_jiguang_net_HttpRequest) {
      return (cn_jiguang_net_HttpRequest()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'jcore_fluttify') as T;
    }
    else if (T == cn_jiguang_net_HttpUtils) {
      return (cn_jiguang_net_HttpUtils()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'jcore_fluttify') as T;
    }
    else if (T == cn_jiguang_net_HttpResponse) {
      return (cn_jiguang_net_HttpResponse()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'jcore_fluttify') as T;
    }
    else if (T == cn_jiguang_internal_JConstants) {
      return (cn_jiguang_internal_JConstants()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'jcore_fluttify') as T;
    }
    else if (T == cn_jiguang_internal_JCoreHelperAction) {
      return (cn_jiguang_internal_JCoreHelperAction()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'jcore_fluttify') as T;
    }
    else if (T == cn_jiguang_internal_JCoreInternalHelper) {
      return (cn_jiguang_internal_JCoreInternalHelper()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'jcore_fluttify') as T;
    }
    else if (T == cn_jiguang_internal_ActionManager) {
      return (cn_jiguang_internal_ActionManager()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'jcore_fluttify') as T;
    }
    else if (T == cn_jiguang_android_IDataShare) {
      return (cn_jiguang_android_IDataShare.subInstance()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'jcore_fluttify') as T;
    }
    else if (T == cn_jiguang_android_IDataShare_Stub) {
      return (cn_jiguang_android_IDataShare_Stub()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'jcore_fluttify') as T;
    }
    else if (T == cn_jiguang_android_BuildConfig) {
      return (cn_jiguang_android_BuildConfig()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'jcore_fluttify') as T;
    }
    else if (T == cn_jiguang_dy_Protocol) {
      return (cn_jiguang_dy_Protocol()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'jcore_fluttify') as T;
    }
    else if (T == cn_jiguang_api_JDispatchAction) {
      return (cn_jiguang_api_JDispatchAction()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'jcore_fluttify') as T;
    }
    else if (T == cn_jiguang_api_JActionExtra) {
      return (cn_jiguang_api_JActionExtra()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'jcore_fluttify') as T;
    }
    else if (T == cn_jiguang_api_utils_ByteBufferUtils) {
      return (cn_jiguang_api_utils_ByteBufferUtils()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'jcore_fluttify') as T;
    }
    else if (T == cn_jiguang_api_utils_OutputDataUtil) {
      return (cn_jiguang_api_utils_OutputDataUtil()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'jcore_fluttify') as T;
    }
    else if (T == cn_jiguang_api_utils_ProtocolUtil) {
      return (cn_jiguang_api_utils_ProtocolUtil()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'jcore_fluttify') as T;
    }
    else if (T == cn_jiguang_api_JRequest) {
      return (cn_jiguang_api_JRequest()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'jcore_fluttify') as T;
    }
    else if (T == cn_jiguang_api_JResponse) {
      return (cn_jiguang_api_JResponse()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'jcore_fluttify') as T;
    }
    else if (T == cn_jiguang_api_JCoreInterface) {
      return (cn_jiguang_api_JCoreInterface()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'jcore_fluttify') as T;
    }
    else if (T == cn_jiguang_api_JCoreManager) {
      return (cn_jiguang_api_JCoreManager()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'jcore_fluttify') as T;
    }
    else if (T == cn_jiguang_api_BaseLogger) {
      return (cn_jiguang_api_BaseLogger()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'jcore_fluttify') as T;
    }
    else if (T == cn_jiguang_api_JProtocol) {
      return (cn_jiguang_api_JProtocol()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'jcore_fluttify') as T;
    }
    else if (T == cn_jiguang_api_MultiSpHelper) {
      return (cn_jiguang_api_MultiSpHelper()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'jcore_fluttify') as T;
    }
    else if (T == cn_jiguang_analytics_page_ActivityLifecycle) {
      return (cn_jiguang_analytics_page_ActivityLifecycle()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'jcore_fluttify') as T;
    }
    else if (T == cn_jiguang_analytics_page_PushSA) {
      return (cn_jiguang_analytics_page_PushSA()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'jcore_fluttify') as T;
    }
    else if (T == cn_jcore_client_android_BuildConfig) {
      return (cn_jcore_client_android_BuildConfig()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'jcore_fluttify') as T;
    }
    else if (T == cn_jpush_android_service_PushService) {
      return (cn_jpush_android_service_PushService()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'jcore_fluttify') as T;
    }
    else if (T == cn_jpush_android_service_DActivity) {
      return (cn_jpush_android_service_DActivity()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'jcore_fluttify') as T;
    }
    else if (T == cn_jpush_android_service_JCommonService) {
      return (cn_jpush_android_service_JCommonService()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'jcore_fluttify') as T;
    }
    else if (T == cn_jpush_android_service_DataProvider) {
      return (cn_jpush_android_service_DataProvider()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'jcore_fluttify') as T;
    }
    else if (T == cn_jpush_android_service_AlarmReceiver) {
      return (cn_jpush_android_service_AlarmReceiver()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'jcore_fluttify') as T;
    }
    else if (T == cn_jpush_android_service_PushReceiver) {
      return (cn_jpush_android_service_PushReceiver()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'jcore_fluttify') as T;
    }
    else if (T == cn_jpush_android_service_WakedResultReceiver) {
      return (cn_jpush_android_service_WakedResultReceiver()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'jcore_fluttify') as T;
    }
    else if (T == cn_jpush_android_service_DownloadActivity) {
      return (cn_jpush_android_service_DownloadActivity()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'jcore_fluttify') as T;
    }
    else if (T == cn_jpush_android_service_DaemonService) {
      return (cn_jpush_android_service_DaemonService()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'jcore_fluttify') as T;
    }
    else if (T == cn_jpush_android_service_DaemonService_MyBinder) {
      return (cn_jpush_android_service_DaemonService_MyBinder()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'jcore_fluttify') as T;
    }
    else if (T == cn_jpush_android_service_DataShare) {
      return (cn_jpush_android_service_DataShare()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'jcore_fluttify') as T;
    }
    else if (T == cn_jpush_android_service_DownloadProvider) {
      return (cn_jpush_android_service_DownloadProvider()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'jcore_fluttify') as T;
    }
    else if (T == android_content_Context) {
      return (android_content_Context()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'jcore_fluttify') as T;
    }
    else if (T == android_content_Intent) {
      return (android_content_Intent()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'jcore_fluttify') as T;
    }
    else if (T == android_content_ContentProvider) {
      return (android_content_ContentProvider()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'jcore_fluttify') as T;
    }
    else if (T == android_app_Application) {
      return (android_app_Application()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'jcore_fluttify') as T;
    }
    else if (T == android_app_Notification) {
      return (android_app_Notification()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'jcore_fluttify') as T;
    }
    else if (T == android_app_Activity) {
      return (android_app_Activity()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'jcore_fluttify') as T;
    }
    else if (T == android_app_PendingIntent) {
      return (android_app_PendingIntent()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'jcore_fluttify') as T;
    }
    else if (T == android_os_Bundle) {
      return (android_os_Bundle()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'jcore_fluttify') as T;
    }
    else if (T == android_os_Binder) {
      return (android_os_Binder()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'jcore_fluttify') as T;
    }
    else if (T == android_view_View) {
      return (android_view_View()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'jcore_fluttify') as T;
    }
    else if (T == android_view_SurfaceView) {
      return (android_view_SurfaceView()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'jcore_fluttify') as T;
    }
    else if (T == android_view_ViewGroup) {
      return (android_view_ViewGroup()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'jcore_fluttify') as T;
    }
    else if (T == android_graphics_Point) {
      return (android_graphics_Point()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'jcore_fluttify') as T;
    }
    else if (T == android_graphics_PointF) {
      return (android_graphics_PointF()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'jcore_fluttify') as T;
    }
    else if (T == android_graphics_Bitmap) {
      return (android_graphics_Bitmap()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'jcore_fluttify') as T;
    }
    else if (T == android_widget_ImageView) {
      return (android_widget_ImageView()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'jcore_fluttify') as T;
    }
    else if (T == java_io_File) {
      return (java_io_File()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'jcore_fluttify') as T;
    }
    else if (T == android_location_Location) {
      return (android_location_Location()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'jcore_fluttify') as T;
    }
    else if (T == android_view_MotionEvent) {
      return (android_view_MotionEvent()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'jcore_fluttify') as T;
    }
    else if (T == android_graphics_drawable_Drawable) {
      return (android_graphics_drawable_Drawable()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'jcore_fluttify') as T;
    }
    else if (T == android_widget_FrameLayout) {
      return (android_widget_FrameLayout()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'jcore_fluttify') as T;
    }
    else if (T == android_widget_TextView) {
      return (android_widget_TextView()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'jcore_fluttify') as T;
    }
    else if (T == android_widget_LinearLayout) {
      return (android_widget_LinearLayout()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'jcore_fluttify') as T;
    }
    else if (T == android_widget_RelativeLayout) {
      return (android_widget_RelativeLayout()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'jcore_fluttify') as T;
    }
    else if (T == android_util_Pair) {
      return (android_util_Pair()..refId = (this is Ref ? (this as Ref).refId : this as int)..tag__ = 'jcore_fluttify') as T;
    }
  }
}