// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import, unused_local_variable, dead_code, unnecessary_cast
//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

import 'dart:typed_data';

import 'package:jcore_fluttify/src/android/android.export.g.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';

import 'package:foundation_fluttify/foundation_fluttify.dart';



mixin cn_jiguang_api_JAction on java_lang_Object {
  

  

  @override
  final String tag__ = 'jcore_fluttify';

  

  

  /* @mustCallSuper */
  Future<bool> isSupportedCMD(int var1) {}
  
  /* @mustCallSuper */
  Future<void> onActionRun(android_content_Context var1, int var2, android_os_Bundle var4, Object var5) {}
  
  /* @mustCallSuper */
  Future<void> onEvent(android_content_Context var1, int var2, int var4) {}
  
  /* @mustCallSuper */
  Future<void> handleMessage(android_content_Context var1, int var2, Object var4) {}
  
  /* @mustCallSuper */
  Future<String> getSdkVersion() {}
  
  /* @mustCallSuper */
  Future<void> dispatchTimeOutMessage(android_content_Context var1, int var2, int var4, int var6) {}
  
}

